import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#f1dbfa',
        'on-secondary-fixed': '#2e004e',
        'on-primary-fixed': '#2b034e',
        'on-primary-container': '#b993df',
        'secondary': '#754c97',
        'outline': '#7c7480',
        'inverse-on-surface': '#fbecff',
        'secondary-fixed-dim': '#e0b6ff',
        'on-surface-variant': '#4b444f',
        'on-tertiary-fixed': '#211b0f',
        'on-primary-fixed-variant': '#59367c',
        'surface-dim': '#e8d3f1',
        'on-surface': '#23162c',
        'surface-container-high': '#f6e1ff',
        'error': '#ba1a1a',
        'primary-fixed': '#f0dbff',
        'surface-tint': '#714f96',
        'inverse-primary': '#dcb8ff',
        'on-secondary-fixed-variant': '#5c347d',
        'primary-fixed-dim': '#dcb8ff',
        'error-container': '#ffdad6',
        'primary-container': '#4a286d',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'tertiary-container': '#40382b',
        'on-secondary-container': '#633b84',
        'on-tertiary-fixed-variant': '#4e4638',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#ada190',
        'surface-container-low': '#fdefff',
        'on-background': '#23162c',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#f9e8ff',
        'surface-variant': '#f1dbfa',
        'primary': '#330f56',
        'secondary-container': '#daacfe',
        'tertiary-fixed': '#eee1ce',
        'outline-variant': '#cdc3d0',
        'background': '#fff7fd',
        'on-primary': '#ffffff',
        'secondary-fixed': '#f2daff',
        'inverse-surface': '#392b42',
        'surface-bright': '#fff7fd',
        'tertiary': '#292317',
        'tertiary-fixed-dim': '#d1c5b2',
        'surface': '#fff7fd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '1.25rem',
        'gutter': '1.5rem',
        'space-2xl': '4rem',
        'gutter-mobile': '1rem',
        'space-xl': '2.5rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'space-lg': '1.75rem',
        'margin': '3rem',
        'space-3xl': '6rem',
        'space-md': '1rem',
      },
      fontFamily: {
        'headline-lg': ['Playfair Display', 'serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'display-hero': ['Playfair Display', 'serif'],
        'display-hero-mobile': ['Playfair Display', 'serif'],
        'label-xs': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '50px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
        'headline-lg-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0em', fontWeight: '500' }],
        'headline-sm': ['22px', { lineHeight: '30px', letterSpacing: '0em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.04em', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-hero': ['56px', { lineHeight: '68px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-hero-mobile': ['38px', { lineHeight: '46px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-xs': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
